export const CREATE_TRANSECTION = "CREATE_TRANSECTION";
export const DELETE_TRANSECTION = "DELETE_TRANSECTION";
export const UPDATE_TRANSECTION = "UPDATE_TRANSECTION";
export const CLEAR_TRANSECTION = "CLEAR_TRANSECTION";
export const INSERT_TRANSECTION = "INSERT_TRANSECTION";
