export const TOGGLE_THEME = "TOGGLE_THEME";
export const SET_THEME = "SET_THEME";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const SET_SIDEBAR = "SET_SIDEBAR";

export const SET_MONTH_FILTER = "SET_MONTH_FILTER";
export const TOGGLE_MONTH_FILTER = "TOGGLE_MONTH_FILTER";

export const SET_AUTOBACKUP = "SET_AUTOBACKUP";
export const SET_AUTOBACKUP_DURATION = "SET_AUTOBACKUP_DURATION";
export const SET_AUTOBACKUP_LAST_TIME = "SET_AUTOBACKUP_LAST_TIME";
